[project]
name = "sortfiles"
version = "1.0.0"
description = "A simple file sorter for all your folder"
authors = [{name = "Jonathan", email = "reinishimiya22@gmail.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.7"

[project.scripts]
sortfiles = "sortfiles.main:main"
